"""Add images column to Hostel model

Revision ID: 451749054bff
Revises: d77a29d4dc15
Create Date: 2026-02-09 10:55:45.682872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451749054bff'
down_revision = 'd77a29d4dc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
