"""Add status column to Review model

Revision ID: d77a29d4dc15
Revises: 86ef7f953ad0
Create Date: 2026-02-09 10:49:58.896136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a29d4dc15'
down_revision = '86ef7f953ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
